### PR TITLE
Deployment scripts

### PR DESCRIPTION
**Pull request by day-jeff**
Provides both Bash and Powershell deployment scripts. The Powershell script uses ARM, while Bash uses CLI. I may switch Powershell to CLI in the future, but it's not a priority right now.

### CODE REVIEW

**Comment by day-jeff** [comment]
Bart comment: I ran into the following issue when I ran with no params
 
Enter your subscription ID [7ab88ae4-5e07-4f96-8371-a493ee29d7af]: 7ab88ae4-5e07-4f96-8371-a493ee29d7af
Using SubscriptionId 7ab88ae4-5e07-4f96-8371-a493ee29d7af.
 
Enter a unique application name: bartr512
./deploy.sh: line 31: allowEmpty: unbound variable

**Comment by day-jeff** [comment]
Bart wrote:

`When you change a setting, the service "should" restart, but it's not always working for me and since we use the /home/LogFiles, I would add the stop / start`

I don't understand this feedback. There isn't any way to change settings in the deployment script.

**Comment by day-jeff** [comment]
Bart wrote:

`I would also add the enable docker CI. It doesn't actually set it up, but I think it's a good practice.`

I opted to use full parameter names to make the script more readable for folks reviewing it.

**Comment by day-jeff** [comment]
Bart wrote:

`Here's a potential error check to validate the region`
 
`az account list-locations  | grep '"name": "eastus3"'
-- returns nothing
az account list-locations  | grep '"name": "eastus"'
-- returns "name": "eastus",`

Good feature request

**Comment by day-jeff** [comment]
Bart wrote:

>Spoke too soon ... the web hook failed again. But when I reran the command it worked.
>
>I think what I would do is curl the webhook as soon as possible in the script. It will fail, but that will force web apps to start it. 
>
>Deploying Event Grid subscription (webhook)...
>+ az eventgrid event-subscription create --name bartr512-webhook --topic-name bartr512-grid --resource-group bartr512 --endpoint https://bartr512.azurewebsites.net/person
>The attempt to validate the provided endpoint https://bartr512.azurewebsites.net/person failed. For more details, visit https://aka.ms/esvalidation.

Nothing is actually failing. The issue is that the app service hasn't started when the webhook is created. This error message actually indicates the web hook WAS created successfully but it can't be validated yet. Short of spinning in a retry loop, which could be several minutes long, I think the solution is to just eat the error.

**Comment by bartr** [comment]
I can't figure out how to reply to a comment, but by change app setting, I meant this line of code:
az webapp config appsettings set ...

The web app should automatically restart after you make that change, but, in my testing, it doesn't. Thus my suggestion to put a "stop" before that line and a "start" after that line. That way you're sure the change takes effect. Since it affects where the log files are written, I would add it.

**Pull request merged**
